# Generated by Django 3.0.3 on 2020-03-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('description', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=220)),
                ('location', models.CharField(max_length=220)),
                ('qualification', models.CharField(max_length=255)),
                ('experience_year', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('job_type', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('skills', models.TextField()),
            ],
            options={
                'db_table': 'job_job',
            },
        ),
    ]
